### ISSUE TITLE
⚙ [CI]: Better dev environment

### ISSUE THREAD

**Issue by iragca** [iragca/page-one-frontend#71]
### As a [role]

Dev

### I need [function]

dfsdfs

### So that [benefit]

Easier development experience

### Details and Assumptions

.env.example
```.env
BACKEND_API_URL="http://localhost:5000"

MONGO_ROOT_USER=root
MONGO_ROOT_PASSWORD=password
MONGODB_PASSWORD=password
MONGODB_DATABASE=pageone

ME_CONFIG_BASICAUTH_USERNAME=user
ME_CONFIG_BASICAUTH_PASSWORD=password

APP_DB_NAME=pageone
APP_DB_USER=user
APP_DB_PASS=password
```

docker-compose.yml

```yml
services:
  page-one_mongodb:
    container_name: backend_mongodb
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    environment:
      MONGODB_ROOT_USER: ${MONGODB_ROOT_USER:-root}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-user}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-pageone}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      timeout: 5s

  page-one_mongoexpress:
    container_name: backend_mongoexpress
    image: 'mongo-express:latest'
    depends_on:
      page-one_mongodb:
        condition: service_healthy
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: backend_mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
      ME_CONFIG_SITE_BASEURL: /mongo-express
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-password}

  backend_insert_data:
    container_name: backend_insert_data
    image: 'iragca/page-one-insert_data:latest'
    depends_on:
      page-one_mongodb:
        condition: service_healthy
    command: [ "sh", "-c", "python insert_data.py" ]

  backend_webapp:
    container_name: backend_webapp
    image: 'iragca/page-one-backend_webapp:latest'
    depends_on:
      page-one_mongodb:
        condition: service_healthy
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://backend_mongodb:27017/pageone?serverSelectionTimeoutMS=2000

```
